# Generated by Django 4.0.4 on 2022-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=100, unique=True)),
                ('sex', models.BooleanField(default=False)),
                ('age', models.SmallIntegerField(default='')),
                ('vege_type', models.CharField(default='', max_length=50)),
                ('alle_type', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
