# Generated by Django 4.0.4 on 2022-05-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alle_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
