# Generated by Django 4.0.4 on 2022-05-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=60),
        ),
    ]
