# Generated by Django 4.0.4 on 2022-05-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alle_type',
            new_name='allergic',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vege_type',
            new_name='vegetype',
        ),
    ]
