# Generated by Django 4.0.4 on 2022-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingre',
            fields=[
                ('ingre_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingre_name', models.CharField(default='', max_length=100, unique=True)),
                ('ingre_group_small', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
