# Generated by Django 4.0.4 on 2022-05-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingre',
            options={'managed': False},
        ),
    ]
