# Generated by Django 4.0.4 on 2022-05-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_ingre_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingre',
            table='ingre',
        ),
    ]
