# Generated by Django 4.0.4 on 2022-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_ingre_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBasic',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('recipe_id', models.IntegerField(blank=True, db_column='RECIPE_ID', null=True)),
                ('recipe_nm_ko', models.TextField(blank=True, db_column='RECIPE_NM_KO', null=True)),
                ('sumry', models.TextField(blank=True, db_column='SUMRY', null=True)),
                ('cooking_time', models.TextField(blank=True, db_column='COOKING_TIME', null=True)),
                ('qnt', models.TextField(blank=True, db_column='QNT', null=True)),
                ('level_nm', models.TextField(blank=True, db_column='LEVEL_NM', null=True)),
                ('img_url', models.TextField(blank=True, db_column='IMG_URL', null=True)),
            ],
            options={
                'db_table': 'recipe_basic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngre',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('recipe_id', models.IntegerField(blank=True, db_column='RECIPE_ID', null=True)),
                ('recipe_nm_ko', models.TextField(blank=True, db_column='RECIPE_NM_KO', null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbo', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('steel', models.FloatField(blank=True, null=True)),
                ('magne', models.FloatField(blank=True, null=True)),
                ('phos', models.FloatField(blank=True, null=True)),
                ('calrium', models.FloatField(blank=True, null=True)),
                ('natrium', models.FloatField(blank=True, null=True)),
                ('copper', models.FloatField(blank=True, null=True)),
                ('selenium', models.FloatField(blank=True, null=True)),
                ('vita_d3', models.FloatField(blank=True, null=True)),
                ('dfe', models.FloatField(blank=True, null=True)),
                ('vita_b12', models.FloatField(blank=True, null=True)),
                ('vita_c', models.FloatField(blank=True, null=True)),
                ('threo', models.FloatField(blank=True, null=True)),
                ('valine', models.FloatField(blank=True, null=True)),
                ('histi', models.FloatField(blank=True, null=True)),
                ('tyrosine', models.FloatField(blank=True, null=True)),
                ('cysteine', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipe_ingre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecipeOrder',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('recipe_id', models.IntegerField(blank=True, db_column='RECIPE_ID', null=True)),
                ('cooking_no', models.IntegerField(blank=True, db_column='COOKING_NO', null=True)),
                ('cooking_dc', models.TextField(blank=True, db_column='COOKING_DC', null=True)),
            ],
            options={
                'db_table': 'recipe_order',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Ingre',
        ),
    ]
