# Generated by Django 4.0.4 on 2022-06-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_recipebasic_recipeingre_recipeorder_delete_ingre'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngreNut',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbo', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('steel', models.FloatField(blank=True, null=True)),
                ('magne', models.FloatField(blank=True, null=True)),
                ('phos', models.FloatField(blank=True, null=True)),
                ('calrium', models.FloatField(blank=True, null=True)),
                ('natrium', models.FloatField(blank=True, null=True)),
                ('zinc', models.FloatField(blank=True, null=True)),
                ('copper', models.FloatField(blank=True, null=True)),
                ('selenium', models.FloatField(blank=True, null=True)),
                ('vita_d3', models.FloatField(blank=True, null=True)),
                ('dfe', models.FloatField(blank=True, null=True)),
                ('vita_b12', models.FloatField(blank=True, null=True)),
                ('vita_c', models.FloatField(blank=True, null=True)),
                ('threo', models.FloatField(blank=True, null=True)),
                ('valine', models.FloatField(blank=True, null=True)),
                ('histi', models.FloatField(blank=True, null=True)),
                ('tyrosine', models.FloatField(blank=True, null=True)),
                ('cysteine', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingre_nut',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='recipeingre',
            name='zinc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
