# Generated by Django 4.0.4 on 2022-06-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_ingrenut_recipeingre_zinc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrenut',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
