# Generated by Django 4.0.4 on 2022-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_alter_ingrenut_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrenut',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False),
        ),
    ]
