# Generated by Django 4.0.4 on 2022-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_alter_ingrenut_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeWhat',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('recipe_id', models.IntegerField(blank=True, db_column='RECIPE_ID', null=True)),
                ('irdnt_nm', models.TextField(blank=True, db_column='IRDNT_NM', null=True)),
                ('irdnt_cpcty', models.TextField(blank=True, db_column='IRDNT_CPCTY', null=True)),
                ('irdnt_nb', models.IntegerField(blank=True, db_column='IRDNT_NB', null=True)),
            ],
            options={
                'db_table': 'recipe_what',
                'managed': True,
            },
        ),
    ]
