# Generated by Django 4.0.4 on 2022-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectIngre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestCombiGlv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='IDX', null=True)),
                ('best_combination', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'best_combi_glv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IngreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='IDX', null=True)),
                ('recipe_id', models.IntegerField(blank=True, db_column='RECIPE_ID', null=True)),
                ('subgroup', models.TextField(blank=True, db_column='SUBGROUP', null=True)),
            ],
            options={
                'db_table': 'ingre_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VegeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='IDX', null=True)),
                ('unnamed_0', models.IntegerField(blank=True, db_column='Unnamed: 0', null=True)),
                ('vege_kinds', models.TextField(blank=True, db_column='VEGE_KINDS', null=True)),
                ('vege_indbl', models.TextField(blank=True, db_column='VEGE_INDBL', null=True)),
            ],
            options={
                'db_table': 'vege_type',
                'managed': True,
            },
        ),
    ]
