# Generated by Django 4.0.4 on 2022-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectIngre', '0002_bestcombiglv_ingrelist_vegetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetype',
            name='idx',
        ),
        migrations.AlterField(
            model_name='vegetype',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False),
        ),
    ]
