# Generated by Django 4.0.4 on 2022-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_nm_ko', models.CharField(blank=True, max_length=30, null=True)),
                ('sumry', models.CharField(blank=True, max_length=100, null=True)),
                ('cooking_time', models.CharField(blank=True, max_length=20, null=True)),
                ('qnt', models.CharField(blank=True, max_length=20, null=True)),
                ('level_nm', models.CharField(blank=True, max_length=20, null=True)),
                ('img_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'recipe_main',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_index', models.IntegerField(max_length=100)),
                ('recipe_id', models.IntegerField(max_length=100)),
                ('recipe_score', models.SmallIntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
