# Generated by Django 4.0.4 on 2022-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPreference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='recipe_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='recipe_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user_index',
            field=models.IntegerField(),
        ),
    ]
