# Generated by Django 3.2.13 on 2022-06-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPreference', '0002_alter_preference_recipe_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
